### ISSUE TITLE
Info on usage

### ISSUE THREAD

**Issue by docop** [ninjadev64/OpenDeck#1]
Hi  So i install the deb file of the last 'auto compile' as no file are put into release. It open up right away, and look quite good. I can go and plugin, if i click download i got msg to install. (no process or succes msg ) then close and when i re-open it show few plugins as being install - with the button remove on thoses.
 But how can i apply to any button ?  There's no menu or + selection to add. And i haven't figure out how to put via file config.
 Do you have an example config file with like using few plugin and some button with app launcher ?

Thanks in advance

**Comment by ninjadev64** [comment]
Hello,

I'm currently working with a couple of other owners of Elgato hardware on the Discord server to get it working, as there are a couple of minor issues with the Elgato hardware support.

I'll have fixes out very soon and will update you when it's ready. In the meantime, you need to install a plugin to provide actions, and then you can drag and drop it onto a key, right click it to customise, and left click to remove it.

**Comment by ninjadev64** [comment]
@docop Support for Elgato hardware is now a lot more stable.

Steps to install the new version:
- Terminate opendeck (`killall opendeck`)
- Remove the old config file (`rm ~/.config/opendeck/config.json`)
- Download the new .deb file from GitHub Actions
- Install the new debfile with `sudo dpkg -i /path/to/opendeck.deb`
- Launch opendeck

Instructions for assigning and configuring actions are detailed in the comment above.

**Comment by docop** [comment]
I did install over a new fresh os And the yesterday version do the same as the previous one. i do see the hand to drag the plugin, and when over one of the placeholder a + sign appear, but it do not 'register/ stay". From the plugin page, It's only the image of the plugin that are 'selectable' to drag over, as the rest is just appear as normal text.. *plugin install as show remove and present in folder /plugins.
 
 Also while you can run the app directly after install and do see the icon over the taskbar, when i do a reboot: i cannot open the app again. No icon on taskbar and clicking over menu/accss/opendesk do nothing. Taskmanager do show it's full auto loaded and active when rebooted. 

 And when i lunch the app (after the install) it's listed at top, with default profile, but the unit itself keep the elgato logo.. Just as when you plug over any usb port. I try to install pkg to see : 

 = libhidapi-libusb0 libxcb-xinerama0 libhidapi-dev  But even installing thoses before dpkg the opendeck .. do still give the same default logo. I was expecting the unit to simply go black and be ready to get button when first run..
 If you can share a config.json file with 3-4 plugins or function on button active to see.. that could help to test out more maybe..
thanks

**Comment by ninjadev64** [comment]
Please see the README file for installation and usage instructions - make sure you've installed it properly, including applying the dev subsystem rules, and then see the animated GIFs that show you how to install plugins, manage profiles, and assign, configure, and remove actions.

**Comment by docop** [comment]
Ho yeah i see what you mean. So over Debian fresh install : when i first open direct after install: the app only show at top right:  stream deck and default. Nothing more !  it's all empty.
 no custom, no clock.. no image no icon! 
To see the empty shell placholder of the unit i have to scroll down. As they are place at about the same height of the 'manage plugins' button.
 yes the udev is present, just doing apt install streamdeck-ui and the unit pop up and i can write txt to button directly. But your app is much more powerfull.. but it don't load icon or so..

**Comment by docop** [comment]
direct in x11 :  running from terminal:
opendeck

libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
(node:1425) UnhandledPromiseRejectionWarning: Error: Command failed: which wine
    at checkExecSyncError (node:child_process:865:11)
    at execSync (node:child_process:936:15)
    at node:electron/js2c/asar_bundle:2:12758
    at new StreamDeckPlugin (/usr/lib/opendeck/resources/app/build/plugins.js:133:59)
    at /usr/lib/opendeck/resources/app/build/plugins.js:237:22
    at Array.forEach (<anonymous>)
    at new StreamDeckPluginManager (/usr/lib/opendeck/resources/app/build/plugins.js:236:24)
    at Object.<anonymous> (/usr/lib/opendeck/resources/app/build/plugins.js:314:25)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
(Use `opendeck --trace-warnings ...` to show where the warning was created)
[1457:1022/162530.939164:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
(node:1425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)


 this open the app : empty : only as post in previous message : only the top right: stream deck, profile. and 2 button at bottom: pluggin and setting.  No icon, all empty.

**Comment by ninjadev64** [comment]
> To see the empty shell placholder of the unit i have to scroll down. As they are place at about the same height of the 'manage plugins' button.

Yep, the app is designed for a 3x3 grid to fit in there, so the window has to be resized to better fit the 5x3 grid of the Stream Deck.

> (node:1425) UnhandledPromiseRejectionWarning: Error: Command failed: which wine

Looks like you don't have Wine installed. Please do install it.

> this open the app : empty : only as post in previous message : only the top right: stream deck, profile. and 2 button at bottom: pluggin and setting. No icon, all empty.

Yes, to get actions that you can assign to keys you need to install a plugin from "Manage plugins", like Visual Studio Code or Clocks.

**Comment by docop** [comment]
Thanks for precision. Indeed, with installing wine : icon pop up in place and i can drag and set the unit.
cool.   
 will need something to used it.. as 1gig just to have a plugin is bit heavy.. hehe

**Comment by ninjadev64** [comment]
> Thanks for precision. Indeed, with installing wine : icon pop up in place and i can drag and set the unit.
> 
> cool.   
> 
>  will need something to used it.. as 1gig just to have a plugin is bit heavy.. hehe

Is it really 1GB? I might need to switch away from Electron... Glad you solved it though!
