### ISSUE TITLE
NixOS packaging question, issue GUI is blank 

### ISSUE THREAD

**Issue by AkechiShiro** [ninjadev64/OpenDeck#15]
Hello,

I'm packaging this for NixOS, but currently I'm running the opendeck binary after building the rust package in `src-tauri` but I'm probably missing the frontend : 
```
** (opendeck:687404): WARNING **: 00:27:33.000: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
[2024-07-24][22:27:33][DEBUG][tiny_http] Server listening on 0.0.0.0:57118
[2024-07-24][22:27:33][DEBUG][tiny_http] Running accept thread
did not find extension DRI_Mesa version 2
did not find extension DRI_IMAGE_DRIVER version 2
failed to bind extensions
did not find extension DRI_Mesa version 2
did not find extension DRI_IMAGE_DRIVER version 2
failed to bind extensions
did not find extension DRI_Mesa version 2
did not find extension DRI_SWRast version 5
failed to bind extensions
Failed to create GBM device for render device: /dev/dri/renderD128: Illegal seek
did not find extension DRI_Mesa version 2
did not find extension DRI_IMAGE_DRIVER version 2
failed to bind extensions
did not find extension DRI_Mesa version 2
did not find extension DRI_IMAGE_DRIVER version 2
failed to bind extensions
did not find extension DRI_Mesa version 2
did not find extension DRI_SWRast version 5
failed to bind extensions
Failed to create GBM device for render device: /dev/dri/renderD128: No such file or directory
Failed to get GBM device
Failed to get GBM device
Failed to get GBM device
```

Would you have any instructions on how to compile the frontend ?

**Comment by ninjadev64** [comment]
Seems like `WEBKIT_DISABLE_COMPOSITING_MODE=1` is the fix.

tauri-apps/tauri#8254

**Comment by ninjadev64** [comment]
Do note that you must also run Tauri apps using the Tauri CLI (`cargo tauri dev`), otherwise when you fix this issue all you'll see is "connection refused". Complete instructions for building/running OpenDeck from source are in the README.

**Comment by AkechiShiro** [comment]
I thought the connection refused was because of udev rules ? Is it something else ?

**Comment by ninjadev64** [comment]
> I thought the connection refused was because of udev rules ? Is it something else ?

Connection refused in the actual window will be because it can't connect to the Vite dev server. Connection refused in the logs / stdout will probably be to do with not being able to connect to a device, yes.

**Comment by ninjadev64** [comment]
> Seems like `WEBKIT_DISABLE_COMPOSITING_MODE=1` is the fix.
> 
> [tauri-apps/tauri#8254](https://github.com/tauri-apps/tauri/issues/8254)

If this fixes it, can I close this issue?

**Comment by AkechiShiro** [comment]
Thanks for the help, I'll close for now, I'll reopen later if I still can't make it work, the AppImage however works fine.

I can use that in the meantime.
