### ISSUE TITLE
Hitting Escape on the plugins page triggers attempt to install last selected plugin, rather than going back.

### ISSUE THREAD

**Issue by thomasvs** [ninjadev64/OpenDeck#21]
I clicked on a plugin.  I tried to install.  It failed.  I hit Esc on the plugin overview.  It asks again if I want to install that previous plugin.  Esc should probably just leave the plugin menu.
![Screenshot from 2024-08-06 22-03-18](https://github.com/user-attachments/assets/dc17b175-c90b-45a4-8714-97a235ffb29f)

**Comment by ninjadev64** [comment]
While I haven't implemented escape closing the menu, now it should at least not trigger the button's event handler.

**Comment by ninjadev64** [comment]
As of 8115dbb <kbd>Escape</kbd> should close all popups in OpenDeck properly.
