### ISSUE TITLE
Cannot find Discord plugin (or any other proprietary plugin)

### ISSUE THREAD

**Issue by dupergg** [ninjadev64/OpenDeck#23]
Hello,

On a previous install, I had the Discord plugin installed and working. After a fresh OS install to Fedora KDE edition, I cannot find the Discord plugin under the plugins section. Not sure what the issue is or how I can fix it.

![image](https://github.com/user-attachments/assets/d16dc849-cd67-48ca-9aa6-498907aa8dce)

**Comment by ninjadev64** [comment]
Sorry for the delay, I forgot to check my emails/GitHub.

I'm not entirely sure what's going on here, when I try the 2.0.0 build I get the same issue and there's an "Unacceptable TLS Certificate" error in the devtools. It doesn't seem to happen for me on the 2.1.0 beta though, so maybe you can fix your problem by updating to that version.

**Comment by ninjadev64** [comment]
@dupergg v2.1.0 is out and should not have this issue.
