### ISSUE TITLE
TypeError: cannot open device with path /dev/hidraw__

### ISSUE THREAD

**Issue by RamboRogers** [ninjadev64/OpenDeck#3]
The automated builds are broken and won't start.  It looks super cool though! Electron can be a bear.
![image](https://github.com/ninjadev64/OpenDeck/assets/7763805/998284cb-09c4-4e03-a592-068505345871)

**Comment by ninjadev64** [comment]
What Linux distro (and kernel version) are you using? This definitely seems like an Electlon bug as myself and many other users have no problems with the automated builds.

Additionally, does it work if you run it yourself (clone the repo and run `npm install && npm run start`)?

**Comment by ninjadev64** [comment]
Oh, completely disregard everything I just said.

This is the same issue as #2, please try the troubleshooting steps I mentioned there.

**Comment by ninjadev64** [comment]
@RamboRogers?

**Comment by RamboRogers** [comment]
![image](https://github.com/ninjadev64/OpenDeck/assets/7763805/e92def99-3218-4e65-87a0-f5a9ade3dbb2)

**Comment by RamboRogers** [comment]
I just installed the package again, from the last unfailed build.

![image](https://github.com/ninjadev64/OpenDeck/assets/7763805/b99acb04-927b-4b4a-87e4-499ad8ece229)

**Comment by ninjadev64** [comment]
Yes, it's not a problem with the build. Please try the troubleshooting steps I detailed in #2.

**Comment by RamboRogers** [comment]
![image](https://github.com/ninjadev64/OpenDeck/assets/7763805/637f201e-01e1-4c23-b23c-aefa8d72a7c9)

I can run Stream Deck UI, which looks sad next to your awesome app. 

![image](https://github.com/ninjadev64/OpenDeck/assets/7763805/956f8efa-271f-47d1-88f7-128486965248)

**Comment by ninjadev64** [comment]
Oh, didn't catch the first screenshot in your last message. The path will be what's in the error message, which for you is `/dev/hidraw6`.

**Comment by ninjadev64** [comment]
@RamboRogers Any luck?
