### ISSUE TITLE
OpenDeck is damaged and can’t be opened on Apple Silicon

### ISSUE THREAD

**Issue by zabit82** [ninjadev64/OpenDeck#31]
not work with apple selicon sequoia 15.1 (24B83)

**Comment by ninjadev64** [comment]
I unfortunately do not have a way to reproduce this issue, as I don't have an Apple Silicon Mac and the app functions fine on my Intel Mac. Maybe try the Intel version through Rosetta.

**Comment by TonyNovikov** [comment]
You can open app after "sudo xattr -cr /Applications/OpenDeck.app" in your terminal. But app says - No devices detected.

**Comment by ninjadev64** [comment]
> You can open app after "sudo xattr -cr /Applications/OpenDeck.app" in your terminal. But app says - No devices detected.

What device do you have?

**Comment by TonyNovikov** [comment]
> > You can open app after "sudo xattr -cr /Applications/OpenDeck.app" in your terminal. But app says - No devices detected.
> 
> What device do you have?

Ajazz AKP153R

**Comment by ninjadev64** [comment]
> > > You can open app after "sudo xattr -cr /Applications/OpenDeck.app" in your terminal. But app says - No devices detected.
> > 
> > What device do you have?
> 
> Ajazz AKP153R 

Device not detected because device not supported 😉 

#10

**Comment by ninjadev64** [comment]
Seems this was either a one time issue or there is an easy workaround posted by Tony, so I will close the issue.

**Comment by vorpalhex** [comment]
This is still occurring on the latest build (2.4.2). This workaround still works.. but I believe the issue is in the ci-pipeline/build system. These attr calls should be happening then. A quick glance didn't reveal anything obvious, maybe this just needs to an extra step for this build?

**Comment by nekename** [comment]
Hmm, I think xattr doesn't actually modify the file but actually updates some local database on your system; doing this step in the CI probably wouldn't help.

Some surface-level Googling revealed that many other apps have this problem, but no one really knows a solution... weird

Out of interest what are you guys actually using OpenDeck on macOS for?

**Comment by nekename** [comment]
Fair enough

**Comment by nekename** [comment]
@zabit82 @TonyNovikov @vorpalhex I've fixed this in https://github.com/nekename/OpenDeck/commit/e16c8920c0415d1035249037b84e314c72cef679 because I now have an Apple Silicon MacBook. Annoyingly, you still have to go into Security and Privacy because the normal right click trick doesn't work in Sequoia or later but it's better than the terminal.

@TonyNovikov You can now use https://github.com/4ndv/opendeck-akp153 for your device.
