### ISSUE TITLE
Install plugins from local files from the GUI

### ISSUE THREAD

**Issue by FelicitusNeko** [ninjadev64/OpenDeck#33]
Since the Elgato Marketplace isn't really an option, but it's still possible to obtain and download plugins from there from within the browser, it would be nice to have an easy way to sideload those plugins into OpenDeck from the GUI.

**Comment by ninjadev64** [comment]
Can and will do. Out of curiosity, how do you download the plugins from marketplace.elgato.com? I've created an account but can only get it to try and open the Stream Deck desktop app.

**Comment by FelicitusNeko** [comment]
It's a bit roundabout. Once you've obtained a plugin, you click on your profile icon at the top-right of the page, "Manage Your Account", then "Products" on the left, find the plugin you want and click on it, then click on the download icon (down arrow with a line underneath).

**Comment by ninjadev64** [comment]
Oh, perfect. It might be easier than I thought to implement downloading plugins from the Marketplace then.
