### ISSUE TITLE
Use something else other than Edge WebView on Windows.

### ISSUE THREAD

**Issue by Unbloated** [ninjadev64/OpenDeck#34]
Hey,

I've noticed your application is using Edge WebView, which is kind of a no-no for me because I've uninstalled Edge and everything that came with it.
Also, because Edge WebView = Edge, it means that most of the telemetry is bundled with it, which is again something that bothers me.

If you can, please try using a telemetry-free webpage embedding way, so I can be sure and cozy about it. Perhaps it would be better for the others too.

Have a nice day !

**Comment by ninjadev64** [comment]
This is not in the scope of OpenDeck and needs to (probably has been already) be raised with Tauri and their `wry` webview rendering library project instead.

<sub><sup>P.S. If you care about telemetry you probably shouldn't be using Windows :wink:</sup></sub>
