### ISSUE TITLE
Statement regarding device support

### ISSUE THREAD

**Issue by ninjadev64** [ninjadev64/OpenDeck#38]
There have been numerous requests for support for various pieces of hardware from various manufacturers over the past few months.

I would like to make it clear that it is not in my interests to spend time implementing interfaces to these devices, especially in the case of those that have comparatively few owners, and even if it were, it is not feasible for me to work on support for a device that I do not own as there is no way to verify that anything works, which results in an arduous, time-consuming back-and-forth with device owners.

For those devices that already have an implementation in some programming language, I have gone out of my way to make it incredibly easy to have these devices supported in OpenDeck by way of a plugin written in said programming language, even if it is not Rust, and am open to providing advice to any owner of said devices with programming skills to do so. For those that do not, I am afraid you will have to have reverse engineering skills and time or wait for someone else who has both.

I am now a maintainer of the upstream [elgato-streamdeck](https://github.com/streamduck-org/elgato-streamdeck) library which provides an interface to Elgato devices and those with similar firmware, notably from MiraBox and subsidiaries (including Ajazz). I will be reviewing and accepting PRs, but will not be making any of my own contributions.

**Comment by glf999** [comment]
AKP153 written into StreamDock 293s firmware cannot be recognized

akp153 ==> 293s
VID 5548 PID 6670 [0300]

**Comment by mattwarner1** [comment]
I'm so sorry to ask what might be a silly question. I see how to edit this library, but how do I compile it into the Open Deck code when I clone it?  I don't see instructions/steps in the documents, but if anyone could help step me through it, I'd really appreciate tips.

**Comment by ninjadev64** [comment]
@mattwarner1 

You just need to replace the specification of the dependency in OpenDeck's Cargo.toml file.

So change it from `elgato-streamdeck = { version = "0.9", ... }` to `elgato-streamdeck = { path = "/path/to/cloned/library", ... }`

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by mattwarner1** [comment]
Thanks, @ninjadev64 , for the tips. I'll give it a shot when I'm a little fresher in the morning. :-)

> [@mattwarner1](https://github.com/mattwarner1)
> 
> You just need to replace the specification of the dependency in OpenDeck's Cargo.toml file.
> 
> So change it from `elgato-streamdeck = { version = "0.9", ... }` to `elgato-streamdeck = { path = "/path/to/cloned/library", ... }`
> 
> https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by nekename** [comment]
v2.5.0 will no longer support Mirabox devices due to somewhat ignorant requests and comments. v2.4.3 will be the last version to support them.

**Comment by nekename** [comment]
@4ndv kindly created and maintains device support plugins for the AKP153/HSV293S range and the AKP03/N3 range. There are also forks of his plugins available for other similar devices and he maintains a library for interfacing with them. 

As such, I will be unpinning this issue as users of these devices are fully covered in OpenDeck v2.5.0 and later even after the removal of inbuilt support.

**Comment by nekename** [comment]
See, I thought relegating these devices to plugins would stop the onslaught of requests. It seems not, so I have to pin this issue again.
