### ISSUE TITLE
Window closes immediately using the Flatpak version

### ISSUE THREAD

**Issue by digilink** [ninjadev64/OpenDeck#39]
Hello, I installed this using a flatpak and it fails to run, this is the messaging received when attempting to run from a flatpak run command: 

```
flatpak run me.amankhanna.opendeck
[2024-12-17][15:38:28][opendeck::events][DEBUG] Registered plugin com.amansprojects.starterpack.sdPlugin

(opendeck:2): Gtk-CRITICAL **: 10:38:28.336: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(opendeck:2): Gtk-CRITICAL **: 10:38:28.338: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
Gdk-Message: 10:38:28.440: Error 71 (Protocol error) dispatching to Wayland display.
```

OS is Fedora 41 with an NVIDIA card (if it matters)

**Comment by ninjadev64** [comment]
I'm pretty sure this error can be ignored.

**Comment by digilink** [comment]
I should add, the app never actually launches, I get a brief showing of a window then it goes away. 

Is wayland potentially the issue?

**Comment by ninjadev64** [comment]
Wayland shouldn't be an issue, I run Wayland. Have you tried the steps in #25?

**Comment by digilink** [comment]
This was the fix, thank you: 

https://github.com/ninjadev64/OpenDeck/issues/25#issuecomment-2392373728

I added this as an environment variable and it works as expected now.

**Comment by ninjadev64** [comment]
Cool! Waiting for the day the Tauri (or more appropriately, WebKit) developers fix this issue...
