### ISSUE TITLE
Release as Flatpak or AppImage?

### ISSUE THREAD

**Issue by NoCodeLeftBehind** [ninjadev64/OpenDeck#4]
Any chance you could build and distribute a Flatpak or AppImage release of this to make it easier to run on a variety of Linux-based devices? There is a similar app on FlatHub, but it is very basic compared to yours. Thanks.

**Comment by ninjadev64** [comment]
Hey - I’m currently working on a rewrite in the tauri-rewrite branch, which
I will publish on Flatpak once complete.

I’ll make an AppImage for the current version in the meantime, however ;)

**Comment by NoCodeLeftBehind** [comment]
> Hey - I’m currently working on a rewrite in the tauri-rewrite branch, which I will publish on Flatpak once complete. I’ll make an AppImage for the current version in the meantime, however ;)

**Comment by ninjadev64** [comment]
Out of curiosity, which Linux distro are you running?

**Comment by NoCodeLeftBehind** [comment]
> Out of curiosity, which Linux distro are you running?

Arch Linux on Steam Deck.

**Comment by NoCodeLeftBehind** [comment]
> > Arch Linux on Steam Deck.
> 
> Cool - I'm not going to make an AppImage release for v1 as there is no official AppImage maker for Electron Forge and the rewrite is almost ready, but the rewrite will go on Flatpak. In addition, a community member has mentioned that they might publish the rewrite to the AUR once it's ready.

Thanks. Looking forward to trying it out.

**Comment by ninjadev64** [comment]
Sorry I haven't gotten back to you. The rewrite has been out for a long while on both Flatpak and AppImage platfoms.
