### ISSUE TITLE
FR: Portable mode on windows

### ISSUE THREAD

**Issue by AtmanActive** [ninjadev64/OpenDeck#41]
Hi,

Thank you very much for this great software. This is awesome!

My experience is about using it on windows.

I would like to suggest a portable running mode where all configuration, plug-ins and icons are stored in directories that are subdirectories of the main directory X that is determined on runtime and is the directory that holds the main opendeck.exe.

Advantages of running windows software in portable mode are numerous: never lose your config and time invested in setting up the software, and, also, have many versions set up in parallel (just by using different folder names), for testing, or for multiple use cases or for multiple machines.

Here is how to make your app work in portable mode, in addition to the existing windows-way mode:

- on app startup, first self-discover your own executed path (do not try to presume some well-known path, like Program Files, for example, but rely on what your run-time exe reports back once running)
- then, check for the existence of a config dir/file in the same folder on that same path.
If it exists, use that config dir/file. If not, continue as normal.

In this way, advanced users can copy or create an empty config file in the same folder where the exe is and take it from there, having all data encapsulated in that one folder, without creating anything on well known windows paths (like C:\Users\xxx). Then, if needed, advanced users can easily copy the whole folder for backups, copy the whole folder to other machines, or, make copies to maintain several versions in parallel.

For non-advanced users, the app continues to work as normal (using C:\Users\xxx).

Thanks!

**Comment by ninjadev64** [comment]
Hi there, apologies; I was in the middle of replying to you last night when my phone died and have been quite busy since then.

Unfortunately I will ask you to bring this up with the developers of the Tauri project for the following reasons:

- OpenDeck uses Tauri's convenient utility functions for directory resolution among other things, and adding additional code to handle a separate case for Windows would not be productive, seeing as Windows is a minority of my apps userbase, and as I would have to use a virtual machine to verify any functionality.

- Implementing this feature in upstream Tauri would benefit many apps built with it, and would not require code changes to any of them.

Thanks,
@ninjadev64

**Comment by AtmanActive** [comment]
Would you mind if I build a wrapper exe that would run opendeck.exe, wait for it to exit and then gather all data from well-known-windows-directory and move it back to exe's directory?

This approach is used for many otherwise non-portable apps at [Portaps](https://portapps.io) and [Portableapps](https://portableapps.com) 

Thanks.

**Comment by ninjadev64** [comment]
Feel free to do whatever you like

**Comment by AtmanActive** [comment]
OK, it's ready here:

[https://github.com/AtmanActive/opendeck-portable](https://github.com/AtmanActive/opendeck-portable)

just in case someone comes this way looking for the same thing.

**Comment by ninjadev64** [comment]
Oh, that's awesome! About the paths in the profiles, 2.4.0 will no longer do that and all paths will be relative to the config directory.

**Comment by ninjadev64** [comment]
@AtmanActive as you know already, 2.4.0 is out so you no longer need to change the config files.

**Comment by AtmanActive** [comment]
@ninjadev64 it's great that you switched to using relative paths, kudos for that, however, I did encounter few places where absolute paths still persist. I'm not sure if that's an oversight in your code or if a plug-in is writing absolute paths.
No biggie, I'll just keep wrap/unwrap running. I just realized I should also wrap/unwrap run-program paths to try to make them relative, if possible (if the destination command is on the same drive as opendeck-portable.exe).



However, I did encounter one bizarre problem I need your help with: 

**- where does opendeck keep the installed/used plug-in list?**

I wanted to get rid of a plug-in, so I deleted it from the plugins folder, but opendeck is bringing it back every time it starts. When I use the UI to check/remove the plugins, the UI shows like there is nothing there. So I can't remove it, but when I try to add it, it fails with the operating system error where a file can't be written over a locked file, of course, since the plugin is already running.

Thanks.

**Comment by ninjadev64** [comment]
> I did encounter few places where absolute paths still persist
That's a shame, could you send me a few examples?

> I wanted to get rid of a plug-in, so I deleted it from the plugins folder, but opendeck is bringing it back every time it starts.
Which plugin is this? Unless it's the built-in Starter Pack plugin, quitting OpenDeck, deleting the folder and opening OpenDeck again should suffice, and that's only if the UI's remove button doesn't work.

**Comment by AtmanActive** [comment]
> > I did encounter few places where absolute paths still persist
> 
> That's a shame, could you send me a few examples?

[Default.zip](https://github.com/user-attachments/files/18550490/Default.zip) line 640



> > I wanted to get rid of a plug-in, so I deleted it from the plugins folder, but opendeck is bringing it back every time it starts.
> 
> Which plugin is this? Unless it's the built-in Starter Pack plugin, quitting OpenDeck, deleting the folder and opening OpenDeck again should suffice, and that's only if the UI's remove button doesn't work.

I figured it out. My bad. Back when I started experimenting with all this, I copied several plug-ins I deemed crucial for my use case straight to opendeck.exe's `plugins` subfolder (where originally only `com.amansprojects.starterpack.sdPlugin resides`), and I completely forgot about it. As expected, opendeck is copying whatever is in that folder to it's data directory's `plugins` folder. It's just that I forgot about it, that's all.

Thanks.

**Comment by AtmanActive** [comment]
But the question remains: where does opendeck keep it's ledger of installed plugins?

Because, if it is only by scanning the plugins subdirectory in it's data directory, then, that is not working reliably here. Sometimes none are mentioned, sometimes just one is mentioned, sometimes all are mentioned. But, this is only about plugin add/remove screen. As long as running the plugins, everything is working flawlessly at all times.

Thanks.

**Comment by ninjadev64** [comment]
It is only scanning that directory. If the plugins aren't appearing in the list, then you might have to reload the opendeck window, I've just remembered I was supposed to fix that for 2.4.0 as well 😓

**Comment by AtmanActive** [comment]
No worries. When you have time. It is important that the keypress-config-plugin execution is working flawlessly, UIs can be fixed later. :)

**Comment by ninjadev64** [comment]
The absolute paths in your config file are written by a plugin, as they are in a `settings` value.

**Comment by ninjadev64** [comment]
I'm not sure what you mean by keypress-config-plugin execution.

**Comment by AtmanActive** [comment]
> I'm not sure what you mean by keypress-config-plugin execution.

I meant, when I press a key on the StreamDeck, then, the configured action is properly executed, even though it uses a plug-in that's not present in the plugins UI (but, of course, is present in the data/plugins directory). Both in the previous version and in the latest version.

**Comment by AtmanActive** [comment]
> The absolute paths in your config file are written by a plugin, as they are in a `settings` value.

Understood. I'll be keeping the JSON path wrap/unwrap enabled in opendeck-portable then.

Thanks.
