### ISSUE TITLE
Plugins are not available immediately after install

### ISSUE THREAD

**Issue by DallasO** [ninjadev64/OpenDeck#5]
After installing a new plugin, following gif from docs or manually installing files, it is not available to drag onto a key.

I must force quit OpenDeck and restart the app to see the new plugins.

I'm also seeing what must be compatibility issues with some Stream Deck apps, causing OpenDeck to be unresponsive or to crash with errors (after force quitting and restarting). Let me know if I should report those separately.

I'm a TS engineer, but have minimal electron experience, and I have some free time. If you could point me in the right direction, I may be able to help solve the related issues.

Related info:
OS: PopOS! 22.04
Deck: MK2
Example Plugins:
- [Analog Clock](https://apps.elgato.com/plugins/com.elgato.analogclock)
- [Home Assistant](https://apps.elgato.com/plugins/de.perdoctus.streamdeck.homeassistant)
- [CPU](https://apps.elgato.com/plugins/com.elgato.cpu)
- [Visual Studio Code](https://apps.elgato.com/plugins/com.nicollasr.streamdeckvsc)

**Comment by ninjadev64** [comment]
Yep, newly installed plugins are not loaded until it launches again. You don't need to force quit, though - you can quit from the app tray or with CTRL+Q.

Could you describe the compatibility issues you're having? I won't fix them for v1 but I can make sure they aren't present in the rewrite.

**Comment by DallasO** [comment]
I see. It would be nice if installed plugins would automatically refresh in the UI, or if there was a refresh button.

I'm excited to see the rewrite - I just got a Stream Deck and I use Linux as my daily so this is the only software I've found that I'll be able to use to configure it.

I'll detail the issues I'm seeing below:

## [Analog Clock](https://apps.elgato.com/plugins/com.elgato.analogclock)
- Time is not displayed, only the plugin thumbnail is shown
  - I'm assuming it should display the current time
- Options to change color, or digital clock do not change the clock on the Stream Deck

## [Home Assistant](https://apps.elgato.com/plugins/de.perdoctus.streamdeck.homeassistant)
- Settings for button Label do not appear to work
- After configuring, saving, and closing the button settings - opening them again results in most settings being empty. The functionality still works though, but all settings must be set again to make a change.
- Sometimes not all options are visible when restarting OpenDeck

## [CPU](https://apps.elgato.com/plugins/com.elgato.cpu) and [Visual Studio Code](https://apps.elgato.com/plugins/com.nicollasr.streamdeckvsc)
- After installation, errors are shown
  - `An error occurred. Try removing any recently installed plugins, and make sure your configured ports are free.`
 ```(node:596984) UnhandledPromiseRejectionWarning: Error: Command failed: which wine
    at checkExecSyncError (node:child_process:865:11)
    at execSync (node:child_process:936:15)
    at node:electron/js2c/asar_bundle:2:12758
    at new StreamDeckPlugin (/usr/lib/opendeck/resources/app/build/plugins.js:133:59)
    at /usr/lib/opendeck/resources/app/build/plugins.js:237:22
    at Array.forEach (<anonymous>)
    at new StreamDeckPluginManager (/usr/lib/opendeck/resources/app/build/plugins.js:236:24)
    at Object.<anonymous> (/usr/lib/opendeck/resources/app/build/plugins.js:314:25)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
```

**Comment by ninjadev64** [comment]
Analog Clock has been previously reported to not work although Elgato’s
other Clocks plugin is one I test with (bear in mind that only one of the
actions from it may work due to some assets the plugin requires are
apparently included in the Stream Deck software itself - this may also be
the reason Analog Clock does not function).

While I have not tried Home Assistant, other users have reported success
with it although I don’t know to what extent - they could have had the same
symptoms as you.

As for CPU and VSCode, these are another two that I test with - could you
try upgrading your Wine to the latest release? (These are Windows
executable plugins and there have been a number of issues with Windows exe
plugins on older Wine versions).

**Comment by DallasO** [comment]
Thank you for the suggestion. Wine was the issue for the CPU and VSCode plugins. 

With the Clocks plugin, I see the correct time in the OpenDeck UI, but my slot on the Stream Deck is empty.

You are welcome to close this issue and I'll await the rewrite so I stop making noise.
