### ISSUE TITLE
No GUI on latest windows build

### ISSUE THREAD

**Issue by cgiesche** [ninjadev64/OpenDeck#6]
Hi ninja,

first of all, thank you for this promising project!

I have issues with the current (https://github.com/ninjadev64/OpenDeck/actions/runs/7629502333) release build on Windows 11:

After the installation, there are 3 "opendeck" processes visible in the task manager but there is no way to open the gui. There is no icon in the taskbar, too. Restarting the app or system does not change the situation.

I am working on a (nearly) freh installed, up to date Windows 11 system with a SD+ connected.

Tell me, if i can provide useful information like logs.

Thanks
Christoph

**Comment by ninjadev64** [comment]
Hi there!

Out of curiosity, why are you using OpenDeck on Windows?

Anyway, if you could run OpenDeck from a command prompt and send over the output, that would be great. Let me know if you're unsure on how to do that.

;)

**Comment by cgiesche** [comment]
Hi,

sorry for my late reply. I can understand your curiosity :D

I would like to switch to Linux, but until now, the Stream Deck has held me back because there was no application that supported the "original" plugins. However, I am developing a plugin myself (https://github.com/cgiesche/streamdeck-homeassistant), and of course, I need a working Stream Deck for that. Therefore, I wanted to try out your application on Windows first.

Meanwhile I had to do a fresh install of my windows. I will check, if the issue is still present and provide logs.

**Comment by ninjadev64** [comment]
> nobody knows, what ANGLE is...

lmaoo

Great you got it working! Also note that OpenDeck has been completely rewritten in Rust in the tauri-rewrite branch, but it hasn't replaced v1 yet as its Elgato hardware support is limited to key up/down and dial events (no images are drawn to the screens).

If you think you'd be able to make some progress on that front feel free to ask about contributing, as I don't own any Elgato hardware which makes it hard for me to develop that feature ;)
