### ISSUE TITLE
Deck Neo Support? 

### ISSUE THREAD

**Issue by snek-the-great** [ninjadev64/OpenDeck#9]
Hi, was wondering if we could get support for the Stream Deck Neo?

**Comment by ninjadev64** [comment]
Hi, looks like the device was only released a few hours ago!

To support the device, it will need to be supported by the elgato-streamdeck library that we use, so you'll have to bring it up with them.

**Comment by AkechiShiro** [comment]
@ninjadev64 Hm is there any way we can inspire ourself from this support in Node : https://github.com/Julusian/node-elgato-stream-deck/issues/87 ? `elgato-streamdeck` lib is written in Python ?

**Comment by ninjadev64** [comment]
Sorry, I'm not sure what you mean. elgato-streamdeck is a _Rust_ library that I do not maintain, merely use, (I do not even own a Stream Deck,) and so any requests for changes to the library should be submitted to its maintainers (notably @TheJebForge).

**Comment by AkechiShiro** [comment]
How can I use the rust library fork I'm working on @ninjadev64  in order to test if I can extend the support to Deck Neo ?

**Comment by ninjadev64** [comment]
@AkechiShiro I've added contributing instructions for OpenDeck to the README today, so follow those first, then change the path of the `elgato-streamdeck` library in src-tauri/Cargo.toml to point to your fork locally ;)

**Comment by AkechiShiro** [comment]
The PR in `elgato-streamdeck` is in draft and I did test it the support works. @ninjadev64

**Comment by AkechiShiro** [comment]
https://github.com/streamduck-org/elgato-streamdeck/pull/10#issuecomment-2154677103

**Comment by ninjadev64** [comment]
> The PR in `elgato-streamdeck` is in draft and I did test it the support works. @ninjadev64

Cool

**Comment by AkechiShiro** [comment]
The PR was merged in the lib, what is left so open deck also has support for Neo ? @ninjadev64

**Comment by ninjadev64** [comment]
> EDIT : A new release of the lib was made, version 0.7.0 with support for Neo.
> 
> I'm guessing bumping the `Cargo.toml` is enough for open deck to have the support.

Once Axias/Guillame's PR is merged, I'll bump the version of this crate so you can use your device in OpenDeck.

**Comment by AkechiShiro** [comment]
I've created a PR if that can help, once you have merged the other PR, you can merge also this one https://github.com/ninjadev64/OpenDeck/pull/13

Thanks for your help !

**Comment by ninjadev64** [comment]
Merged, thanks!

**Comment by AkechiShiro** [comment]
Thanks a lot too ! 
Can a new release be done for the Neo support to be packaged upstream @ninjadev64 ?

**Comment by ninjadev64** [comment]
I'll be publishing a new release soon, maybe this weekend.

**Comment by AkechiShiro** [comment]
Hey, just pinging again ! For the new release, if you have time this week-end !

**Comment by ninjadev64** [comment]
Hey @AkechiShiro 

I had built a release earlier today, but had forgotten to publish it. Here you go!

https://github.com/ninjadev64/OpenDeck/releases/tag/v2.0.0-beta.9
